FROM continuumio/miniconda3:23.10.0-1

RUN apt update
RUN apt install -y libopenblas0-openmp

RUN conda install -y -c defaults mkl numpy==1.23.5 scipy scikit-learn numexpr pandas r-base
RUN pip install intel-tensorflow-avx512==2.12.0

RUN mkdir /root/.R/
RUN echo "CFLAGS=-march=native" >>/root/.R/Makevars
RUN echo "CXXFLAGS=-march=native" >>/root/.R/Makevars

COPY . /app
WORKDIR /app
RUN Rscript requirements.R
